/** 將 API error code 轉成使用者可讀中文 */
const API_ERROR_ZH: Record<string, string> = {
  REASON_REQUIRED: "請填寫取消原因",
  NOT_FOUND: "找不到資料",
  FORBIDDEN: "沒有權限",
  UNAUTHORIZED: "請先登入",
  DB: "資料庫錯誤，請稍後再試或聯絡管理員",
  BANNED: "帳號已停權",
  INVALID_BODY: "資料不完整",
  INVALID_PACE: "配速設定無效",
  PACE_OUT_OF_RANGE: "配速超出允許範圍",
  INVALID_START: "開始時間無效",
  LOCATION_REQUIRED: "請選擇集合點",
  BANQIAO_ONLY: "一般會員僅能選擇板橋區集合點",
  TIME_OVERLAP: "時段與其他活動重疊",
  RUN_CLOSED: "活動已結束或關閉",
  ALREADY_CLOSED: "活動已結束，無法操作",
  HOST_MUST_CANCEL_RUN: "主揪請改用「取消整場活動」",
  NOT_REGISTERED: "尚未報名此活動",
  INVALID_MINUTES: "延期分鐘數需為 1–30",
  DELAY_LIMIT: "延期次數已達上限",
  DELAY_TOTAL_LIMIT: "累計延期已達上限",
  CANCELLED: "活動已取消",
  ALREADY_COMPLETED: "活動已結案",
  NOT_CANCELLED: "活動尚未取消",
  HOST_EXEMPT: "此主揪免於惡意取消投票",
  NOT_PARTICIPANT: "僅報名者可投票",
  CANNOT_VOTE_SELF: "無法對自己投票",
  INVALID_CONTENT: "留言內容無效",
  COOLDOWN: "送出太頻繁，請稍候再試",
  COMMENT_ID_REQUIRED: "缺少留言編號",
  CANNOT_FOLLOW_SELF: "無法追蹤自己",
  HOST_NOT_FOUND: "找不到主揪",
  INVALID_SUBSCRIPTION: "推播訂閱資料無效",
  USER_REQUIRED: "請指定使用者",
  CANNOT_BLOCK_SELF: "無法封鎖自己",
  NOT_BANNED: "帳號未停權，無需申訴",
  ALREADY_PENDING: "已有待審申訴",
  TITLE_REQUIRED: "請填寫名稱",
  ID_REQUIRED: "缺少編號",
  INVALID_ROLE: "角色無效",
  FULL: "名額已滿",
  BLOCKED: "你已被此主揪封鎖",
  ALREADY_REGISTERED: "已報名此活動",
  USER_NOT_FOUND: "找不到使用者",
  RUN_NOT_FOUND: "找不到活動",
  VAPID_NOT_CONFIGURED: "伺服器尚未設定推播金鑰，請聯絡管理員",
  VAPID_INVALID: "伺服器推播金鑰格式錯誤，請聯絡管理員",
  SELF_NO_PUSH: "你尚未開啟推播，請先到「我的」開啟後再測試",
};

export function apiErrorMessage(code: unknown, fallback = "操作失敗"): string {
  if (typeof code !== "string" || !code) return fallback;
  return API_ERROR_ZH[code] ?? fallback;
}
